# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        options: 
        - patch
        - minor
        - major

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup git user
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Bump Version
      run: npm version ${{ github.event.inputs.name }} 
      
      
    - name: Push changes
      run: git push --tags  
      
    - name: Create github release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create `echo $(git describe --tags --abbrev=0)` --generate-notes
   
