# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  workflow_dispatch: 
    inputs:
      branch:
        type: choice
        description: What branch to deploy to
        options:
         - stage
         - prod
      
      version:
        type: string
        description: What version tag to deploy
        
  workflow_call:
    inputs:
      branch:
        type: string
        description: What branch to deploy to
        default: stage
      
      version:
        type: string
        description: What version tag to deploy

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        
    - name: Push to branch
      run: |
        git fetch --tags
        git merge ${{ inputs.version }}
        git push
